######Edit Add#######

        self.Add_frame = QtWidgets.QFrame(self.Edit_Tab)
        self.Add_frame.setGeometry(QtCore.QRect(10, 160, 301, 241))
        self.Add_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.Add_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Add_frame.setObjectName("Add_frame")
        self.Add_column = QtWidgets.QComboBox(self.Add_frame)
        self.Add_column.setGeometry(QtCore.QRect(140, 60, 128, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Add_column.setFont(font)
        self.Add_column.setEditable(True)
        self.Add_column.setObjectName("Add_column")
        self.Add_column.addItem("")
        self.Add_column.setItemText(0, "")
        self.Add_column.addItem("")
        self.Add_column.addItem("")
        self.Add_position = QtWidgets.QComboBox(self.Add_frame)
        self.Add_position.setGeometry(QtCore.QRect(140, 110, 128, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Add_position.setFont(font)
        self.Add_position.setObjectName("Add_position")
        self.Add_position.addItem("")
        self.Add_position.addItem("")
        self.Add_newText = QtWidgets.QLineEdit(self.Add_frame)
        self.Add_newText.setGeometry(QtCore.QRect(140, 160, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Add_newText.setFont(font)
        self.Add_newText.setAutoFillBackground(False)
        self.Add_newText.setObjectName("Add_newText")
        self.Add_start = QtWidgets.QPushButton(self.Add_frame)
        self.Add_start.setGeometry(QtCore.QRect(180, 200, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Add_start.setFont(font)
        self.Add_start.setObjectName("Add_start")
        self.label_11 = QtWidgets.QLabel(self.Add_frame)
        self.label_11.setGeometry(QtCore.QRect(10, 60, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Add_frame)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Add_frame)
        self.label_13.setGeometry(QtCore.QRect(10, 160, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Add_frame)
        self.label_14.setGeometry(QtCore.QRect(0, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")

####Edit Remove####

        self.Remove_frame = QtWidgets.QFrame(self.Edit_Tab)
        self.Remove_frame.setGeometry(QtCore.QRect(10, 160, 301, 241))
        self.Remove_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.Remove_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Remove_frame.setObjectName("Remove_frame")
        self.Remove_column = QtWidgets.QComboBox(self.Remove_frame)
        self.Remove_column.setGeometry(QtCore.QRect(140, 60, 128, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Remove_column.setFont(font)
        self.Remove_column.setEditable(True)
        self.Remove_column.setObjectName("Remove_column")
        self.Remove_column.addItem("")
        self.Remove_column.setItemText(0, "")
        self.Remove_column.addItem("")
        self.Remove_column.addItem("")
        self.Remove_position = QtWidgets.QComboBox(self.Remove_frame)
        self.Remove_position.setGeometry(QtCore.QRect(140, 110, 128, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Remove_position.setFont(font)
        self.Remove_position.setObjectName("Remove_position")
        self.Remove_position.addItem("")
        self.Remove_position.addItem("")
        self.Remove_oldText = QtWidgets.QLineEdit(self.Remove_frame)
        self.Remove_oldText.setGeometry(QtCore.QRect(140, 160, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Remove_oldText.setFont(font)
        self.Remove_oldText.setAutoFillBackground(False)
        self.Remove_oldText.setObjectName("Remove_oldText")
        self.Remove_start = QtWidgets.QPushButton(self.Remove_frame)
        self.Remove_start.setGeometry(QtCore.QRect(180, 200, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Remove_start.setFont(font)
        self.Remove_start.setObjectName("Remove_start")
        self.label_11 = QtWidgets.QLabel(self.Remove_frame)
        self.label_11.setGeometry(QtCore.QRect(10, 60, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Remove_frame)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Remove_frame)
        self.label_13.setGeometry(QtCore.QRect(10, 160, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Remove_frame)
        self.label_14.setGeometry(QtCore.QRect(0, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")

####Edit Replace#####

        self.Replace_frame = QtWidgets.QFrame(self.Edit_Tab)
        self.Replace_frame.setGeometry(QtCore.QRect(10, 160, 301, 280))
        self.Replace_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.Replace_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Replace_frame.setObjectName("Replace_frame")
        self.label_14 = QtWidgets.QLabel(self.Replace_frame)
        self.label_14.setGeometry(QtCore.QRect(0, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.Replace_column = QtWidgets.QComboBox(self.Replace_frame)
        self.Replace_column.setGeometry(QtCore.QRect(140, 50, 130, 30))
        self.Replace_column.setEditable(True)
        self.Replace_column.setObjectName("Replace_column")
        self.Replace_column.addItem("")
        self.Replace_column.setItemText(0, "")
        self.Replace_column.addItem("")
        self.Replace_column.addItem("")
        self.Replace_position = QtWidgets.QComboBox(self.Replace_frame)
        self.Replace_position.setGeometry(QtCore.QRect(140, 100, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Replace_position.setFont(font)
        self.Replace_position.setObjectName("Replace_position")
        self.Replace_position.addItem("")
        self.Replace_position.addItem("")
        self.Replace_position.addItem("")
        self.Replace_position.addItem("")
        self.Replace_oldtext = QtWidgets.QLineEdit(self.Replace_frame)
        self.Replace_oldtext.setGeometry(QtCore.QRect(140, 150, 133, 30))
        self.Replace_oldtext.setObjectName("Replace_oldtext")
        self.Replace_newtext = QtWidgets.QLineEdit(self.Replace_frame)
        self.Replace_newtext.setGeometry(QtCore.QRect(140, 200, 133, 30))
        self.Replace_newtext.setObjectName("Replace_newtext")
        self.Replace_start = QtWidgets.QPushButton(self.Replace_frame)
        self.Replace_start.setGeometry(QtCore.QRect(200, 240, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Replace_start.setFont(font)
        self.Replace_start.setObjectName("Replace_start")
        self.label_11 = QtWidgets.QLabel(self.Replace_frame)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Replace_frame)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Replace_frame)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.Replace_frame)
        self.label_15.setGeometry(QtCore.QRect(10, 200, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")

#####Edit Irregular#####

        self.Irreg_frame = QtWidgets.QFrame(self.Edit_Tab)
        self.Irreg_frame.setGeometry(QtCore.QRect(10, 160, 301, 241))
        self.Irreg_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.Irreg_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Irreg_frame.setObjectName("Irreg_frame")
        self.label_14 = QtWidgets.QLabel(self.Irreg_frame)
        self.label_14.setGeometry(QtCore.QRect(0, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.Irreg_cons = QtWidgets.QLineEdit(self.Irreg_frame)
        self.Irreg_cons.setGeometry(QtCore.QRect(140, 60, 130, 30))
        self.Irreg_cons.setObjectName("Irreg_cons")
        self.Irreg_oldinflec = QtWidgets.QLineEdit(self.Irreg_frame)
        self.Irreg_oldinflec.setGeometry(QtCore.QRect(140, 110, 130, 30))
        self.Irreg_oldinflec.setObjectName("Irreg_oldinflec")
        self.irreg_newinflec = QtWidgets.QLineEdit(self.Irreg_frame)
        self.irreg_newinflec.setGeometry(QtCore.QRect(140, 160, 130, 30))
        self.irreg_newinflec.setObjectName("irreg_newinflec")
        self.Irreg_start = QtWidgets.QPushButton(self.Irreg_frame)
        self.Irreg_start.setGeometry(QtCore.QRect(180, 200, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Irreg_start.setFont(font)
        self.Irreg_start.setObjectName("Irreg_start")
        self.label_11 = QtWidgets.QLabel(self.Irreg_frame)
        self.label_11.setGeometry(QtCore.QRect(10, 60, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Irreg_frame)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Irreg_frame)
        self.label_13.setGeometry(QtCore.QRect(10, 160, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
